### ISSUE TITLE
ModuleNotFoundError: No module named 'windows_tools'

### ISSUE THREAD

**Issue by pre22** [netinvent/windows_tools#5]
```
    from windows_tools.installed_software import get_installed_software

ModuleNotFoundError: No module named 'windows_tools'
```

I got the above error when trying to run the script

**Comment by deajan** [comment]
I'll need more info to help here.
How did you install windows_tools ?
What's your environnement ?

**Comment by pre22** [comment]
Installation was successful using pip but on got an error pointing to the line above.
I'm using Python 3.10, Windows 8.1

**Comment by deajan** [comment]
The installation was probably not successful at all. Closing this in favor of #6
