### ISSUE TITLE
No Antivirus Detected

### ISSUE THREAD

**Issue by pizzpea1** [netinvent/windows_tools#9]
Hello, is your program working correctly? i just ran it and it returned this:

Example code for tests.windows_tools.antivirus, 2021020901
Antivirus software:

[]

Why is there no windows defender?

**Comment by pizzpea1** [comment]
windows defender shows if there are other AVs installed, but not if it's the only one. There should be a workaround

**Comment by pizzpea1** [comment]
I'm on windows 10, not running as admin, it only shows windows admin when there are other antiviruses installed. If windows defender is the only antivirus, it does not appear in the list

**Comment by deajan** [comment]
Mind to re-test with latest fix ?

**Comment by negativeproton** [comment]
Just FYI:
```python
>>> import windows_tools.antivirus
>>> result = windows_tools.antivirus.get_installed_antivirus_software()
>>> result
[{'name': 'Windows Defender', 'version': None, 'publisher': None, 'enabled': True, 'is_up_to_date': True, 'type': 'Windows Defender / Security Essentials'}]
```
with the current project state and the setup described in https://github.com/netinvent/windows_tools/issues/10:
## works for me now :) except for version and publisher
tested as admin

"Keys version and publisher are only filled via installed software list." - [README.md](https://github.com/netinvent/windows_tools#readme)

## How can the values for these keys be filled?

**Comment by deajan** [comment]
Thanks for your report.
Version and publisher keys can't be filled using securityCenter wmi calls... The info is not présent.

**Comment by deajan** [comment]
LGFM
